import { Outfit } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from '@/components/ui/sonner';
// app/layout.js
import { LanguageProvider } from './providers/LanguageProvider';
// import { useLanguage } from '@/providers/LanguageProvider';
import { Providers } from './providers/Providers';

const inter = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  // const { language } = useLanguage();

  // const clerkLocalization = {
  //   ko: {
  //     signIn: {
  //       start: {
  //         title: '로그인',
  //         subtitle: '계정에 로그인하세요',
  //         actionText: '계정이 없으신가요?',
  //         actionLink: '가입하기',
  //       },
  //       password: {
  //         title: '비밀번호를 입력하세요',
  //         placeholder: '비밀번호',
  //         actionText: '비밀번호를 잊으셨나요?',
  //         actionLink: '재설정',
  //       },
  //     },
  //     userButton: {
  //       action__manage_account: '계정 관리',
  //       action__sign_out: '로그아웃',
  //       action__sign_in: '로그인',
  //       action__sign_up: '가입하기',
  //     },
  //   },
  //   // Add other languages as needed
  // };

  return (
    <html>
      <body>
        {/* <ClerkProvider localization={clerkLocalization[language]}> */}
        <LanguageProvider>
          <Providers>
            {children}

            <Toaster position='top-center' />
          </Providers>
        </LanguageProvider>
        {/* </ClerkProvider> */}
      </body>
    </html>

    // <LanguageProvider>
    //   <ClerkProvider>
    //     <html lang='en'>
    //       <body className={inter.className}>
    //         <Toaster />
    //         {children}
    //       </body>
    //     </html>
    //   </ClerkProvider>
    // </LanguageProvider>
  );
}
