// utils/terms-content.js
export const termsContent = {
  en: {
    title: 'Terms of Service',
    lastUpdated: 'Last Updated: December 12, 2024',
    sections: [
      {
        title: '1. Acceptance of Terms',
        content: `By accessing and using AI-Interview ("the Service"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our service.`,
      },
      {
        title: '2. Use of Service',
        content: `Our service provides AI-powered interview practice. We do not guarantee job placement or interview success. The service is for practice purposes only.`,
      },
      {
        title: '3. User Accounts',
        content: `You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account.`,
      },
      {
        title: '4. Privacy',
        content: `Your use of the Service is also governed by our Privacy Policy. By using the Service, you consent to the collection and use of information as detailed in our Privacy Policy.`,
      },
      {
        title: '5. Content',
        content: `The questions, answers, and feedback generated by our AI are for reference only. We do not guarantee their accuracy or appropriateness for any specific interview situation.`,
      },
      {
        title: '6. Recording',
        content: `By using our recording features, you agree that you are solely responsible for the content you record and share through our service.`,
      },
      {
        title: '7. Modifications',
        content: `We reserve the right to modify these terms at any time. We will notify users of any material changes via email or through the Service.`,
      },
    ],
    contact: {
      title: 'Contact Us',
      content:
        'If you have any questions about these Terms, please contact us at:',
    },
  },
  ko: {
    title: '서비스 이용약관',
    lastUpdated: '최종 수정일: 2024년 12월 12일',
    sections: [
      {
        title: '1. 약관 동의',
        content: `AI-Interview ("서비스")에 접속하고 이용함으로써, 귀하는 본 이용약관에 동의하게 됩니다. 약관의 어떤 부분에도 동의하지 않는 경우 서비스를 이용할 수 없습니다.`,
      },
      {
        title: '2. 서비스 이용',
        content: `본 서비스는 AI 기반 면접 연습을 제공합니다. 취업이나 면접 성공을 보장하지 않으며, 연습 목적으로만 사용됩니다.`,
      },
      {
        title: '3. 사용자 계정',
        content: `귀하는 계정과 비밀번호의 기밀성을 유지할 책임이 있습니다. 귀하의 계정에서 발생하는 모든 활동에 대한 책임을 수락하는 것에 동의합니다.`,
      },
      {
        title: '4. 개인정보',
        content: `서비스 이용은 개인정보처리방침의 적용을 받습니다. 서비스를 이용함으로써 개인정보처리방침에 상세히 기술된 정보의 수집 및 사용에 동의하게 됩니다.`,
      },
      {
        title: '5. 콘텐츠',
        content: `AI가 생성한 질문, 답변 및 피드백은 참고용으로만 제공됩니다. 특정 면접 상황에 대한 정확성이나 적절성을 보장하지 않습니다.`,
      },
      {
        title: '6. 녹음',
        content: `녹음 기능을 사용함으로써, 귀하는 녹음하고 공유하는 콘텐츠에 대해 전적인 책임이 있음에 동의합니다.`,
      },
      {
        title: '7. 약관 수정',
        content: `당사는 언제든지 이용약관을 수정할 권리를 보유합니다. 중요한 변경사항이 있는 경우 이메일이나 서비스를 통해 사용자에게 통지합니다.`,
      },
    ],
    contact: {
      title: '문의하기',
      content: '이용약관에 대한 문의사항이 있으시면 아래로 연락해 주세요:',
    },
  },
};
